# Generated by Django 3.2.21 on 2023-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exotic_cuisine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username2', models.CharField(max_length=50)),
                ('table_id2', models.IntegerField()),
                ('bdate2', models.DateTimeField()),
                ('timeslot2', models.IntegerField()),
            ],
        ),
    ]
