# Generated by Django 3.2.21 on 2023-09-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exotic_cuisine', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test2',
        ),
    ]
