# Generated by Django 3.2.21 on 2023-09-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exotic_cuisine', '0003_rename_test_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username3', models.CharField(max_length=50)),
                ('table_id3', models.IntegerField()),
                ('bdate3', models.DateTimeField()),
                ('timeslot3', models.IntegerField()),
            ],
        ),
    ]
