# Generated by Django 3.2.21 on 2023-09-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exotic_cuisine', '0005_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='exotic_cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('authour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exotic_cuisine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
