# Generated by Django 3.2.21 on 2023-09-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exotic_cuisine', '0006_exotic_cuisine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
        migrations.DeleteModel(
            name='Test3',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
